export const BROADCAST_CHANNEL_NAME = "EXPOFP_BROADCAST_CHANNEL_NAME";
export const MESSAGE_CACHE = "EXPOFP_MESSAGE_CACHE";
export const MESSAGE_REFRESH = "EXPOFP_MESSAGE_REFRESH";
export const MESSAGE_CACHE_BUNDLE = "EXPOFP_MESSAGE_CACHE_BUNDLE";
