name: Deploy CI

# Trigger on any push
on: push
# on:
#     push:
#         branches:
#             - master
#     pull_request:
#         branches:
#             - master
#         types: [closed]

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'skip-ci')"

        strategy:
            matrix:
                node-version: [20.x]

        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
            CI: true
            AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
            CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AwsCloudFrontDistributionID }}
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true

        steps:
            - uses: actions/checkout@v2

            - name: Extract branch name
              shell: bash
              run: echo "AWS_FOLDER_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - run: yarn install

            - run: yarn run build+deploy

            - name: Send Slack message on push
              if: github.event_name == 'push'
              uses: slackapi/slack-github-action@v1.26.0
              with:
                  payload: |
                      {
                        "blocks": [
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*Event Type:* `${{ github.event_name }}`\n*Repository:* <${{ github.event.repository.html_url }}>\n*Commit:* <${{ github.event.repository.html_url }}/commit/${{ github.sha }}>\n*Author:* <https://github.com/${{ github.actor }}>\n*Date and Time:* `${{ github.event.head_commit.timestamp }}`
                            }
                          }
                        ]
                      }

            - name: Send Slack message on PR merge
              if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
              uses: slackapi/slack-github-action@v1.26.0
              with:
                  payload: |
                      {
                        "blocks": [
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*Event Type:* `${{ github.event_name }}`\n*Repository:* <${{ github.event.repository.html_url }}>\n*Pull Request:* <${{ github.event.pull_request.html_url }}>\n*Commit:* <${{ github.event.repository.html_url }}/commit/${{ github.event.pull_request.head.sha }}>\n*Author:* <https://github.com/${{ github.actor }}>\n*Date and Time:* `${{ github.event.pull_request.merged_at }}`
                            }
                          }
                        ]
                      }
